  - type: entity
    parent: BaseItem
    id: BaseBoardEntity
    name: board
    description: A blank board.
    abstract: true
    components:
      - type: TabletopGame
        size: 256, 256
        setup: !type:TabletopEmptySetup
          boardPrototype: Crowbar
  - type: entity
    parent: BaseItem
    id: BaseTabletopPiece
    abstract: true
    components:
      - type: Sprite
        noRot: true
      - type: Appearance
      - type: Tag
        tags: [TabletopPiece]
      - type: TabletopDraggable
  - type: entity
    id: BaseBoardTabletop
    name: baseboard
    abstract: true
    categories: [HideSpawnMenu]
    components:
      - type: Sprite
        noRot: false
        drawdepth: FloorTiles
      - type: Tag
        tags: [TabletopBoard]
