  - type: entity
    parent: BaseItem
    id: BasePart
    name: body part
    abstract: true
    components:
      - type: StaticPrice
        price: 100
      - type: Tag
        tags:
          - Trash
  # Shitmed Change Start
      - type: Destructible
        thresholds:
          - trigger: !type:DamageTypeTrigger
              damageType: Blunt
              damage: 110
            behaviors:
              - !type:GibPartBehavior {}
          - trigger: !type:DamageTypeTrigger
              damageType: Slash
              damage: 150
            behaviors:
              - !type:GibPartBehavior {}
          - trigger: !type:DamageTypeTrigger
              damageType: Heat
              damage: 200
            behaviors:
              - !type:SpawnEntitiesBehavior
                spawnInContainer: true
                spawn:
                  Ash:
                    min: 1
                    max: 1
              - !type:BurnBodyBehavior {}
              - !type:PlaySoundBehavior
                sound:
                  collection: MeatLaserImpact
  # Shitmed Change End
      - type: Damageable
        damageContainer: OrganicPart # Shitmed Change
      - type: ContainerContainer
        containers:
          bodypart: !type:Container
            ents: []
      - type: BodyPart
      - type: Gibbable
      - type: SurgeryTool
        startSound:
          path: /Audio/_Shitmed/Medical/Surgery/organ1.ogg
        endSound:
          path: /Audio/_Shitmed/Medical/Surgery/organ2.ogg
  - type: entity
    parent: BasePart
    id: BaseTorso
    name: torso
    abstract: true
    components:
      - type: Destructible
        thresholds:
          - trigger: !type:DamageTypeTrigger
              damageType: Blunt
              damage: 400
            behaviors:
              - !type:GibPartBehavior {}
          - trigger: !type:DamageTypeTrigger
              damageType: Slash
              damage: 400
            behaviors:
              - !type:GibPartBehavior {}
          - trigger: !type:DamageTypeTrigger
              damageType: Heat
              damage: 400
            behaviors:
              - !type:SpawnEntitiesBehavior
                spawnInContainer: true
                spawn:
                  Ash:
                    min: 1
                    max: 1
              - !type:BurnBodyBehavior {}
              - !type:PlaySoundBehavior
                sound:
                  collection: MeatLaserImpact
    # Shitmed Change End
      - type: ContainerContainer
        containers:
          torso_slot: !type:ContainerSlot {}
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 11
        staminaCost: 12
      - type: BodyPart
        partType: Torso
    # Shitmed Change Start
        toolName: a torso
        containerName: torso_slot
  - type: entity
    parent: BasePart
    id: BaseHead
    name: head
    abstract: true
    components:
      - type: Tag
        tags: [Head]
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 5
        staminaCost: 5
      - type: BodyPart
        partType: Head
        toolName: a head # Shitmed Change
        vital: true
      - type: Input
        context: ghost
  - type: entity
    parent: BasePart
    id: BaseLeftArm
    name: left arm
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 7
        staminaCost: 7
      - type: BodyPart
        partType: Arm
        symmetry: Left
        toolName: a left arm # Shitmed Change
  - type: entity
    parent: BasePart
    id: BaseRightArm
    name: right arm
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 7
        staminaCost: 7
      - type: BodyPart
        partType: Arm
        symmetry: Right
        toolName: a right arm # Shitmed Change
  - type: entity
    parent: BasePart
    id: BaseLeftHand
    name: left hand
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 3
      - type: BodyPart
        partType: Hand
        symmetry: Left
        toolName: a left hand # Shitmed Change
  - type: entity
    parent: BasePart
    id: BaseRightHand
    name: right hand
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 3
      - type: BodyPart
        partType: Hand
        symmetry: Right
        toolName: a right hand # Shitmed Change
  - type: entity
    parent: BasePart
    id: BaseLeftLeg
    name: left leg
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 8
        staminaCost: 9
      - type: BodyPart
        partType: Leg
        symmetry: Left
        toolName: a left leg # Shitmed Change
      - type: MovementBodyPart
  - type: entity
    parent: BasePart
    id: BaseRightLeg
    name: right leg
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 8
        staminaCost: 9
      - type: BodyPart
        partType: Leg
        symmetry: Right
        toolName: a right leg # Shitmed Change
      - type: MovementBodyPart
  - type: entity
    parent: BasePart
    id: BaseLeftFoot
    name: left foot
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 4
      - type: BodyPart
        partType: Foot
        symmetry: Left
        toolName: a left foot # Shitmed Change
  - type: entity
    parent: BasePart
    id: BaseRightFoot
    name: right foot
    abstract: true
    components:
      - type: DamageOtherOnHit
        damage:
          types:
            Blunt: 4
      - type: BodyPart
        partType: Foot
        symmetry: Right
        toolName: a right foot # Shitmed Change
